# yml for combined validation datasets
project:
  proj_dirs:
  - /home/nthom/Documents/opensphere/project/custom_ms1m_sfnet20_sphereface2_identity_mworks12
CAV_data:
  source_name: DoppelVer
  concept_data_path: /home/nthom/Downloads/Doppelganger/Images/CCA_Images/
  num_concepts_to_select: 390
parallel:
  device_ids: [0]
